config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos, only: %i(index new create edit update)
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  include Abyme::Model
  has_many :todo_items, inverse_of: :todo, dependent: :destroy

  abyme_for :todo_items
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to edit_todo_path(@todo)
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to edit_todo_path(@todo)
  end


  private

  def todo_params
    params.require(:todo).permit(:title, todo_items_attributes: [:id, :content, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/abyme/_todo_item_fields.html.erb
<div class="max-w-sm rounded overflow-hidden shadow-lg">
  <div class="px-6 py-4">
    <div class="md:w-2/3 mb-4">
      <%= f.input :content, input_html: { class: 'main-input' } %>
      <%= f.hidden_field :_destroy %>
    </div>
  </div>
  <div class="px-6 pt-4 pb-2">
    <%= remove_association %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorexp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mx-auto">
  <%= link_to 'todo', todos_path %>
</div>

app/views/todos/_form.html.erb
  <%= simple_form_for todo do |f| %>
    <%= f.input :title, input_html: { class: 'main-input text-gray-700 text-base mb-8' } %>

    <%= abymize(:todo_items, f) do |abyme| %> 
      <div class="w-full float-right mb-8">
        <%= abyme.records(fields_html: { class: 'flex flex-wrap float-left md:w-1/4 sm:w-1/2' }) %>
        <%= abyme.new_records(fields_html: { class: 'flex flex-wrap float-left md:w-1/4 sm:w-1/2' }) %>
      </div>
      <%= add_association %>
    <% end %>

    <%= f.submit %>
  <% end %>

app/views/todos/edit.html.erb
<div class="container mx-auto pt-12">
  <div class="font-bold text-xl mb-2">New Todo</div>
  <%= render 'form', todo: @todo %>
</div>

app/views/todos/index.html.erb
<div class="container mx-auto">
  
</div>

app/views/todos/new.html.erb
<div class="container mx-auto pt-12">
  <%= simple_form_for @todo do |f| %>
    <div class="md:w-2/3 mb-4">
      <%= f.input :title, input_html: { class: 'main-input' } %>
    </div>

    <%= abymize(:todo_items, f) %>
  <% end %>
</div>